version: '3.8'

services:
  ai-extractor:
    build:
      context: .
      dockerfile: Dockerfile.ai-extractor
    ports:
      - "9009:9009"
    environment:
      # 支持多种AI提供商配置
      # 豆包AI (字节跳动) - 推荐
      - ARK_API_KEY=${ARK_API_KEY:-your_ark_api_key}
      - ARK_BASE_URL=${ARK_BASE_URL:-https://ark.cn-beijing.volces.com/api/v3}
      - ARK_MODEL=${ARK_MODEL:-doubao-1-5-pro-32k-250115}
      
      # 智谱AI
      # - OPENAI_API_KEY=${OPENAI_API_KEY:-your_zhipu_api_key}
      # - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://open.bigmodel.cn/api/paas/v4}
      # - OPENAI_MODEL=${OPENAI_MODEL:-glm-4-flash}
      
      # OpenAI兼容接口
      # - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      # - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      # - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9009/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - AI_ASSIST_ENABLED=true
      - AI_EXTRACTOR_URL=http://ai-extractor:9009/ai/extract/v1
      - RULES_FILE_PATH=/app/engine/rules_v33.py
      # 传递AI配置到后端
      - ARK_API_KEY=${ARK_API_KEY:-}
      - ARK_BASE_URL=${ARK_BASE_URL:-}
      - ARK_MODEL=${ARK_MODEL:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-}
    depends_on:
      - ai-extractor
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./samples:/app/samples
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  data:
  logs: